name: unittest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - development

jobs:
  run-unittest:
    name: Unitest job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        uses: Gr1N/setup-poetry@v5

      - name: Install dependencies
        run: poetry install

      - name: Runs unittest
        run: poetry run python -m unittest -v
